# Generated by Django 2.2.13 on 2022-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp288', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'МУЖЧИНА'), ('female', 'ЖЕНЩИНА'), ('other', 'ДРУГИЕ')],
                                   max_length=10),
        ),
    ]
