# Generated by Django 2.2.13 on 2022-04-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0002_auto_20220413_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp169', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('english', 'АНГЛИЙСКИЙ'), ('russian', 'РУССКИЙ'), ('uzbek', 'УЗБЕКСКИЙ'),
                                            ('french', 'ФРАНЦУЗСКИЙ')], default='english', max_length=10),
        ),
    ]
