# Generated by Django 2.2.13 on 2022-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0003_auto_20220413_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp382', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
