# Generated by Django 2.2.13 on 2022-04-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0005_auto_20220413_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp767', max_length=70),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(
                choices=[('approved', 'ОДОБРЕННЫЙ'), ('unapproved', 'НЕ УТВЕРЖДЕНО'), ('decline', 'ОТКЛОНЕННЫЙ')],
                default='Not Approved', max_length=15),
        ),
    ]
