# Generated by Django 4.0.4 on 2022-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_employee_emp_id_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Q', 'Qoraqalpogʻiston'), ('XV', 'Xorazm viloyati'), ('NAV', 'Navoiy viloyati'), ('BV', 'Buxoro viloyati'), ('SAV', 'Samarqand viloyati'), ('QV', 'Qashqadaryo viloyati'), ('SUV', 'Surxondaryo viloyati'), ('JV', 'Jizzax viloyati'), ('SIV', 'Sirdaryo viloyati'), ('TV', 'Toshkent viloyati'), ('NMV', 'Namangan viloyati'), ('FV', 'Fargʻona viloyati'), ('AV', 'Andijon viloyati'), ('T', 'Toshkent shahri')], default='T', max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp781', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('tashkent', 'АНГЛИЙСКИЙ'), ('russian', 'РУССКИЙ'), ('uzbek', 'УЗБЕКСКИЙ'), ('french', 'ФРАНЦУЗСКИЙ')], default='english', max_length=10),
        ),
    ]
