# Generated by Django 4.0.4 on 2022-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_employee_region_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp285', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Andijon viloyati', 'Andijon viloyati'), ('Toshkent shahri', 'Toshkent shahri')], default='Toshkent shahri', max_length=40),
        ),
    ]
